//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MaaAahwanamEntities : DbContext
    {
        public MaaAahwanamEntities()
            : base("name=MaaAahwanamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MaaAahwanam_Others_AllRegisteredUsersDetails_Result> MaaAahwanam_Others_AllRegisteredUsersDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_AllRegisteredUsersDetails_Result>("MaaAahwanam_Others_AllRegisteredUsersDetails");
        }
    
        public virtual ObjectResult<MaaAahwanam_Others_RegisteredUsers_Result> MaaAahwanam_Others_RegisteredUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_RegisteredUsers_Result>("MaaAahwanam_Others_RegisteredUsers");
        }
    
        public virtual ObjectResult<MaaAahwanam_Others_RegisteredUsersDetails_Result> MaaAahwanam_Others_RegisteredUsersDetails(Nullable<long> userLoginId)
        {
            var userLoginIdParameter = userLoginId.HasValue ?
                new ObjectParameter("UserLoginId", userLoginId) :
                new ObjectParameter("UserLoginId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_RegisteredUsersDetails_Result>("MaaAahwanam_Others_RegisteredUsersDetails", userLoginIdParameter);
        }
    
        public virtual ObjectResult<SP_vendordatesbooked_Result> SP_vendordatesbooked(Nullable<int> vID)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("VID", vID) :
                new ObjectParameter("VID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_vendordatesbooked_Result>("SP_vendordatesbooked", vIDParameter);
        }
    
        public virtual ObjectResult<MaaAahwanam_Services_Bidding_Result> MaaAahwanam_Services_Bidding(Nullable<long> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Services_Bidding_Result>("MaaAahwanam_Services_Bidding", requestIdParameter);
        }
    
        public virtual ObjectResult<MaaAahwanam_Others_Comments_Result> MaaAahwanam_Others_Comments(Nullable<long> commentId)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("CommentId", commentId) :
                new ObjectParameter("CommentId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_Comments_Result>("MaaAahwanam_Others_Comments", commentIdParameter);
        }
    
        public virtual ObjectResult<MaaAahwanam_Others_Tickets_Result> MaaAahwanam_Others_Tickets(Nullable<long> ticketId)
        {
            var ticketIdParameter = ticketId.HasValue ?
                new ObjectParameter("TicketId", ticketId) :
                new ObjectParameter("TicketId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_Tickets_Result>("MaaAahwanam_Others_Tickets", ticketIdParameter);
        }
    
        public virtual ObjectResult<sp_Servicedetails_Result> sp_Servicedetails(Nullable<long> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Servicedetails_Result>("sp_Servicedetails", requestIdParameter);
        }
    
        public virtual ObjectResult<allnotifications_Result> allnotifications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allnotifications_Result>("allnotifications");
        }
    
        public virtual ObjectResult<sp_QuotationComments_Result> sp_QuotationComments(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_QuotationComments_Result>("sp_QuotationComments", idParameter);
        }
    
        public virtual ObjectResult<sp_ServiceComments_Result> sp_ServiceComments(Nullable<long> serviceId)
        {
            var serviceIdParameter = serviceId.HasValue ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ServiceComments_Result>("sp_ServiceComments", serviceIdParameter);
        }
    
        public virtual ObjectResult<serviceconfirmation_Result> serviceconfirmation(Nullable<int> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<serviceconfirmation_Result>("serviceconfirmation", requestIDParameter);
        }
    
        public virtual ObjectResult<sp_Tickets_Result> sp_Tickets(Nullable<long> ticketId)
        {
            var ticketIdParameter = ticketId.HasValue ?
                new ObjectParameter("TicketId", ticketId) :
                new ObjectParameter("TicketId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tickets_Result>("sp_Tickets", ticketIdParameter);
        }
    
        public virtual ObjectResult<GetDealServiceType_Result> GetDealServiceType(string ntype)
        {
            var ntypeParameter = ntype != null ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDealServiceType_Result>("GetDealServiceType", ntypeParameter);
        }
    
        public virtual ObjectResult<orderconfirmation_Result> orderconfirmation(Nullable<int> oID)
        {
            var oIDParameter = oID.HasValue ?
                new ObjectParameter("OID", oID) :
                new ObjectParameter("OID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<orderconfirmation_Result>("orderconfirmation", oIDParameter);
        }
    
        public virtual ObjectResult<GetProducts_Result> GetProducts(string nType, Nullable<int> vID, string stype, string landmark, string order)
        {
            var nTypeParameter = nType != null ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(string));
    
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("VID", vID) :
                new ObjectParameter("VID", typeof(int));
    
            var stypeParameter = stype != null ?
                new ObjectParameter("stype", stype) :
                new ObjectParameter("stype", typeof(string));
    
            var landmarkParameter = landmark != null ?
                new ObjectParameter("Landmark", landmark) :
                new ObjectParameter("Landmark", typeof(string));
    
            var orderParameter = order != null ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts", nTypeParameter, vIDParameter, stypeParameter, landmarkParameter, orderParameter);
        }
    
        public virtual ObjectResult<sp_indexdeals_Result> sp_indexdeals(string nType)
        {
            var nTypeParameter = nType != null ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_indexdeals_Result>("sp_indexdeals", nTypeParameter);
        }
    
        public virtual ObjectResult<SP_Deals_Result> SP_Deals(string nType, Nullable<int> vID, string stype, string city, string order)
        {
            var nTypeParameter = nType != null ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(string));
    
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("VID", vID) :
                new ObjectParameter("VID", typeof(int));
    
            var stypeParameter = stype != null ?
                new ObjectParameter("stype", stype) :
                new ObjectParameter("stype", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var orderParameter = order != null ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Deals_Result>("SP_Deals", nTypeParameter, vIDParameter, stypeParameter, cityParameter, orderParameter);
        }
    
        public virtual ObjectResult<ProductsDisplay_Result> ProductsDisplay(string nType, Nullable<int> vID, string stype, string landmark, string order)
        {
            var nTypeParameter = nType != null ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(string));
    
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("VID", vID) :
                new ObjectParameter("VID", typeof(int));
    
            var stypeParameter = stype != null ?
                new ObjectParameter("stype", stype) :
                new ObjectParameter("stype", typeof(string));
    
            var landmarkParameter = landmark != null ?
                new ObjectParameter("Landmark", landmark) :
                new ObjectParameter("Landmark", typeof(string));
    
            var orderParameter = order != null ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductsDisplay_Result>("ProductsDisplay", nTypeParameter, vIDParameter, stypeParameter, landmarkParameter, orderParameter);
        }
    
        public virtual ObjectResult<cartcount_Result> cartcount(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cartcount_Result>("cartcount", idParameter);
        }
    
        public virtual ObjectResult<sp_AllOrders_Result> sp_AllOrders(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AllOrders_Result>("sp_AllOrders", idParameter);
        }
    
        public virtual ObjectResult<MaaAahwanam_Orders_OrderDetails_Result> MaaAahwanam_Orders_OrderDetails(Nullable<long> orderNo)
        {
            var orderNoParameter = orderNo.HasValue ?
                new ObjectParameter("OrderNo", orderNo) :
                new ObjectParameter("OrderNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Orders_OrderDetails_Result>("MaaAahwanam_Orders_OrderDetails", orderNoParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> ratingscount(Nullable<long> vid, Nullable<long> subid, string type)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(long));
    
            var subidParameter = subid.HasValue ?
                new ObjectParameter("subid", subid) :
                new ObjectParameter("subid", typeof(long));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("ratingscount", vidParameter, subidParameter, typeParameter);
        }
    
        public virtual ObjectResult<MaaAahwanam_Others_Testimonials_Result> MaaAahwanam_Others_Testimonials()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_Testimonials_Result>("MaaAahwanam_Others_Testimonials");
        }
    
        public virtual ObjectResult<ServicesRecordView_Result> ServicesRecordView(Nullable<long> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServicesRecordView_Result>("ServicesRecordView", requestIdParameter);
        }
    
        public virtual ObjectResult<MaaAahwanam_Others_TestimonialDetail_Result> MaaAahwanam_Others_TestimonialDetail(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaaAahwanam_Others_TestimonialDetail_Result>("MaaAahwanam_Others_TestimonialDetail", idParameter);
        }
    
        public virtual ObjectResult<SP_Amenities_Result> SP_Amenities(Nullable<long> vendorid, string ntype)
        {
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("vendorid", vendorid) :
                new ObjectParameter("vendorid", typeof(long));
    
            var ntypeParameter = ntype != null ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Amenities_Result>("SP_Amenities", vendoridParameter, ntypeParameter);
        }
    
        public virtual ObjectResult<SP_dealsinfo_Result> SP_dealsinfo(Nullable<int> vid, string nType, Nullable<int> vid2, Nullable<int> did)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            var nTypeParameter = nType != null ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(string));
    
            var vid2Parameter = vid2.HasValue ?
                new ObjectParameter("Vid2", vid2) :
                new ObjectParameter("Vid2", typeof(int));
    
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_dealsinfo_Result>("SP_dealsinfo", vidParameter, nTypeParameter, vid2Parameter, didParameter);
        }
    
        public virtual ObjectResult<geteventsandtipsimages_Result> geteventsandtipsimages(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<geteventsandtipsimages_Result>("geteventsandtipsimages", idParameter);
        }
    
        public virtual ObjectResult<Deal_Result> Deal(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Deal_Result>("Deal", typeParameter);
        }
    
        public virtual ObjectResult<vendorallservices_Result> vendorallservices(string type, Nullable<long> id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vendorallservices_Result>("vendorallservices", typeParameter, idParameter);
        }
    
        public virtual ObjectResult<AllVendorList_Result> AllVendorList(string servicType)
        {
            var servicTypeParameter = servicType != null ?
                new ObjectParameter("ServicType", servicType) :
                new ObjectParameter("ServicType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllVendorList_Result>("AllVendorList", servicTypeParameter);
        }
    
        public virtual ObjectResult<searchvendors_Result> searchvendors(string type, string param)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchvendors_Result>("searchvendors", typeParameter, paramParameter);
        }
    
        public virtual ObjectResult<spsearchword_Result> spsearchword(string search, string type)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spsearchword_Result>("spsearchword", searchParameter, typeParameter);
        }
    
        public virtual ObjectResult<spsearchdeal_Result> spsearchdeal(string search, string type)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spsearchdeal_Result>("spsearchdeal", searchParameter, typeParameter);
        }
    
        public virtual ObjectResult<spsearchdealname_Result> spsearchdealname(string name, string type)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spsearchdealname_Result>("spsearchdealname", nameParameter, typeParameter);
        }
    
        public virtual ObjectResult<vendorproducts_Result> vendorproducts(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vendorproducts_Result>("vendorproducts", typeParameter);
        }
    
        public virtual ObjectResult<searchvendorproducts_Result> searchvendorproducts(string searchitem, string type)
        {
            var searchitemParameter = searchitem != null ?
                new ObjectParameter("searchitem", searchitem) :
                new ObjectParameter("searchitem", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchvendorproducts_Result>("searchvendorproducts", searchitemParameter, typeParameter);
        }
    
        public virtual ObjectResult<Spgetalldeals_Result> Spgetalldeals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Spgetalldeals_Result>("Spgetalldeals");
        }
    
        public virtual ObjectResult<GetCartItemsnew_Result> GetCartItemsnew(Nullable<int> vID)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("VID", vID) :
                new ObjectParameter("VID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItemsnew_Result>("GetCartItemsnew", vIDParameter);
        }
    
        public virtual ObjectResult<Spalldeals_Result> Spalldeals(Nullable<int> id, string type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Spalldeals_Result>("Spalldeals", idParameter, typeParameter);
        }
    
        public virtual ObjectResult<filtervendors_Result> filtervendors(string type, string f1, string f2, string f3)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var f1Parameter = f1 != null ?
                new ObjectParameter("f1", f1) :
                new ObjectParameter("f1", typeof(string));
    
            var f2Parameter = f2 != null ?
                new ObjectParameter("f2", f2) :
                new ObjectParameter("f2", typeof(string));
    
            var f3Parameter = f3 != null ?
                new ObjectParameter("f3", f3) :
                new ObjectParameter("f3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filtervendors_Result>("filtervendors", typeParameter, f1Parameter, f2Parameter, f3Parameter);
        }
    
        public virtual ObjectResult<addvendorservices_Result> addvendorservices(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<addvendorservices_Result>("addvendorservices", idParameter);
        }
    
        public virtual ObjectResult<SPGETNDeal_Result> SPGETNDeal(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGETNDeal_Result>("SPGETNDeal", idParameter);
        }
    
        public virtual ObjectResult<SPgetpartdeal_Result> SPgetpartdeal(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPgetpartdeal_Result>("SPgetpartdeal", idParameter);
        }
    
        public virtual ObjectResult<sp_ordersdisplay_Result> sp_ordersdisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ordersdisplay_Result>("sp_ordersdisplay");
        }
    
        public virtual ObjectResult<speventvdeals_Result> speventvdeals(string vid, string type, Nullable<System.DateTime> date)
        {
            var vidParameter = vid != null ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<speventvdeals_Result>("speventvdeals", vidParameter, typeParameter, dateParameter);
        }
    
        public virtual ObjectResult<Spgetalleventdeals_Result> Spgetalleventdeals(string eve, Nullable<System.DateTime> date)
        {
            var eveParameter = eve != null ?
                new ObjectParameter("eve", eve) :
                new ObjectParameter("eve", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Spgetalleventdeals_Result>("Spgetalleventdeals", eveParameter, dateParameter);
        }
    
        public virtual ObjectResult<GetProductsInfo_Result> GetProductsInfo(Nullable<int> vid, string nType, Nullable<int> vid2)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            var nTypeParameter = nType != null ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(string));
    
            var vid2Parameter = vid2.HasValue ?
                new ObjectParameter("Vid2", vid2) :
                new ObjectParameter("Vid2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsInfo_Result>("GetProductsInfo", vidParameter, nTypeParameter, vid2Parameter);
        }
    
        public virtual ObjectResult<getservicetype_Result> getservicetype(string ntype)
        {
            var ntypeParameter = ntype != null ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getservicetype_Result>("getservicetype", ntypeParameter);
        }
    
        public virtual ObjectResult<filtervendordates_Result> filtervendordates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filtervendordates_Result>("filtervendordates");
        }
    
        public virtual ObjectResult<GetCartItems_Result> GetCartItems(Nullable<int> vID)
        {
            var vIDParameter = vID.HasValue ?
                new ObjectParameter("VID", vID) :
                new ObjectParameter("VID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItems_Result>("GetCartItems", vIDParameter);
        }
    
        public virtual ObjectResult<sp_LeastBidRecord_Result> sp_LeastBidRecord(Nullable<long> requestId)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LeastBidRecord_Result>("sp_LeastBidRecord", requestIdParameter);
        }
    
        public virtual ObjectResult<sp_OrderDetails_Result> sp_OrderDetails(Nullable<long> orderBy)
        {
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OrderDetails_Result>("sp_OrderDetails", orderByParameter);
        }
    
        public virtual ObjectResult<packagevendordates_Result> packagevendordates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<packagevendordates_Result>("packagevendordates");
        }
    
        public virtual ObjectResult<SPGETpartpkg_Result> SPGETpartpkg(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGETpartpkg_Result>("SPGETpartpkg", idParameter);
        }
    
        public virtual ObjectResult<SPGETNpkg_Result> SPGETNpkg(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGETNpkg_Result>("SPGETNpkg", idParameter);
        }
    
        public virtual ObjectResult<sp_userorddisplay_Result> sp_userorddisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_userorddisplay_Result>("sp_userorddisplay");
        }
    
        public virtual ObjectResult<sp_vendoruserorddisplay_Result> sp_vendoruserorddisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vendoruserorddisplay_Result>("sp_vendoruserorddisplay");
        }
    
        public virtual ObjectResult<sp_userordlist_Result> sp_userordlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_userordlist_Result>("sp_userordlist");
        }
    
        public virtual ObjectResult<sp_allorddetail_Result> sp_allorddetail(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_allorddetail_Result>("sp_allorddetail", typeParameter);
        }
    
        public virtual ObjectResult<sp_allvendoruserorddisplay_Result> sp_allvendoruserorddisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_allvendoruserorddisplay_Result>("sp_allvendoruserorddisplay");
        }
    
        public virtual ObjectResult<sp_customers_Result> sp_customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_customers_Result>("sp_customers");
        }
    
        public virtual ObjectResult<GetFilteredVendors_Result> GetFilteredVendors(string type, string name)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFilteredVendors_Result>("GetFilteredVendors", typeParameter, nameParameter);
        }
    
        public virtual ObjectResult<VendorsDatesbooked_Result> VendorsDatesbooked(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VendorsDatesbooked_Result>("VendorsDatesbooked", idParameter);
        }
    
        public virtual ObjectResult<GetCaterers_Result> GetCaterers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCaterers_Result>("GetCaterers");
        }
    
        public virtual ObjectResult<GetDecorators_Result> GetDecorators()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDecorators_Result>("GetDecorators");
        }
    
        public virtual ObjectResult<GetOthers_Result> GetOthers(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOthers_Result>("GetOthers", typeParameter);
        }
    
        public virtual ObjectResult<GetVendors_Result> GetVendors(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVendors_Result>("GetVendors", typeParameter);
        }
    
        public virtual ObjectResult<GetPhotographers_Result> GetPhotographers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPhotographers_Result>("GetPhotographers");
        }
    
        public virtual ObjectResult<Getwedding_Result> Getwedding(string ceremony)
        {
            var ceremonyParameter = ceremony != null ?
                new ObjectParameter("ceremony", ceremony) :
                new ObjectParameter("ceremony", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwedding_Result>("Getwedding", ceremonyParameter);
        }
    
        public virtual ObjectResult<SP_Getvendormasterdata_Result> SP_Getvendormasterdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Getvendormasterdata_Result>("SP_Getvendormasterdata");
        }
    
        public virtual ObjectResult<GetCategoryByname_Result> GetCategoryByname(string categorytype)
        {
            var categorytypeParameter = categorytype != null ?
                new ObjectParameter("categorytype", categorytype) :
                new ObjectParameter("categorytype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategoryByname_Result>("GetCategoryByname", categorytypeParameter);
        }
    
        public virtual ObjectResult<Getvendor_category_vendorid_Result> Getvendor_category_vendorid(Nullable<int> categoryId, Nullable<long> vendorid)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("vendorid", vendorid) :
                new ObjectParameter("vendorid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getvendor_category_vendorid_Result>("Getvendor_category_vendorid", categoryIdParameter, vendoridParameter);
        }
    
        public virtual ObjectResult<Ceremonydetails_Result> Ceremonydetails(string ceremony)
        {
            var ceremonyParameter = ceremony != null ?
                new ObjectParameter("ceremony", ceremony) :
                new ObjectParameter("ceremony", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ceremonydetails_Result>("Ceremonydetails", ceremonyParameter);
        }
    
        public virtual ObjectResult<GetwishlistDetails_Result> GetwishlistDetails(Nullable<long> wishlistid)
        {
            var wishlistidParameter = wishlistid.HasValue ?
                new ObjectParameter("wishlistid", wishlistid) :
                new ObjectParameter("wishlistid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetwishlistDetails_Result>("GetwishlistDetails", wishlistidParameter);
        }
    
        public virtual ObjectResult<Getdetailsofwishlistitem_Result> Getdetailsofwishlistitem(Nullable<long> vendorid)
        {
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("vendorid", vendorid) :
                new ObjectParameter("vendorid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getdetailsofwishlistitem_Result>("Getdetailsofwishlistitem", vendoridParameter);
        }
    
        public virtual ObjectResult<Getwishlistdetails_userid_Result> Getwishlistdetails_userid(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwishlistdetails_userid_Result>("Getwishlistdetails_userid", useridParameter);
        }
    
        public virtual ObjectResult<Getwishlistvendors_Result> Getwishlistvendors(Nullable<long> wishlistid, Nullable<int> categoryid)
        {
            var wishlistidParameter = wishlistid.HasValue ?
                new ObjectParameter("wishlistid", wishlistid) :
                new ObjectParameter("wishlistid", typeof(long));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwishlistvendors_Result>("Getwishlistvendors", wishlistidParameter, categoryidParameter);
        }
    
        public virtual ObjectResult<Getmyprofile_Result> Getmyprofile(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getmyprofile_Result>("Getmyprofile", tokenParameter);
        }
    
        public virtual ObjectResult<SP_GetTestimonials_Result> SP_GetTestimonials()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTestimonials_Result>("SP_GetTestimonials");
        }
    
        public virtual ObjectResult<sharedwishlist_Result> sharedwishlist(string sharedemail)
        {
            var sharedemailParameter = sharedemail != null ?
                new ObjectParameter("sharedemail", sharedemail) :
                new ObjectParameter("sharedemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sharedwishlist_Result>("sharedwishlist", sharedemailParameter);
        }
    
        public virtual ObjectResult<wishlistitemavailable_Result> wishlistitemavailable(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wishlistitemavailable_Result>("wishlistitemavailable", useridParameter);
        }
    
        public virtual ObjectResult<allcategories_Result> allcategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allcategories_Result>("allcategories");
        }
    
        public virtual ObjectResult<getcategorieslst_Result> getcategorieslst()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getcategorieslst_Result>("getcategorieslst");
        }
    
        public virtual ObjectResult<getallvendorevalue_Result> getallvendorevalue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallvendorevalue_Result>("getallvendorevalue");
        }
    
        public virtual ObjectResult<Getwishlisdata_vendorid_Result> Getwishlisdata_vendorid(Nullable<long> vendorid)
        {
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("vendorid", vendorid) :
                new ObjectParameter("vendorid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwishlisdata_vendorid_Result>("Getwishlisdata_vendorid", vendoridParameter);
        }
    
        public virtual ObjectResult<browevendors_Result> browevendors(Nullable<int> categoryid)
        {
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<browevendors_Result>("browevendors", categoryidParameter);
        }
    
        public virtual ObjectResult<Getvendor_vendorid_Result> Getvendor_vendorid(Nullable<long> vendorid)
        {
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("vendorid", vendorid) :
                new ObjectParameter("vendorid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getvendor_vendorid_Result>("Getvendor_vendorid", vendoridParameter);
        }
    
        public virtual ObjectResult<getuserlogindetails_Result> getuserlogindetails(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getuserlogindetails_Result>("getuserlogindetails", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<categoriesbycid_Result> categoriesbycid(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<categoriesbycid_Result>("categoriesbycid", cidParameter);
        }
    
        public virtual ObjectResult<Ceremonydetails_id_Result> Ceremonydetails_id(Nullable<long> ceremonyid)
        {
            var ceremonyidParameter = ceremonyid.HasValue ?
                new ObjectParameter("ceremonyid", ceremonyid) :
                new ObjectParameter("ceremonyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ceremonydetails_id_Result>("Ceremonydetails_id", ceremonyidParameter);
        }
    
        public virtual ObjectResult<GetVendorsByCategoryId_Result> GetVendorsByCategoryId(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVendorsByCategoryId_Result>("GetVendorsByCategoryId", categoryIdParameter);
        }
    
        public virtual ObjectResult<getuserdetailsforadmin_Result> getuserdetailsforadmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getuserdetailsforadmin_Result>("getuserdetailsforadmin");
        }
    
        public virtual ObjectResult<Getwishlistdetails_user_Result> Getwishlistdetails_user(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwishlistdetails_user_Result>("Getwishlistdetails_user", tokenParameter);
        }
    
        public virtual ObjectResult<Getwishlistdetails_token_categoryid_Result> Getwishlistdetails_token_categoryid(string token, Nullable<int> categoryid)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwishlistdetails_token_categoryid_Result>("Getwishlistdetails_token_categoryid", tokenParameter, categoryidParameter);
        }
    
        public virtual ObjectResult<getvendoralldetails_Result> getvendoralldetails(string token, Nullable<int> categoryid)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getvendoralldetails_Result>("getvendoralldetails", tokenParameter, categoryidParameter);
        }
    
        public virtual ObjectResult<getalldetailsofvendors_Result> getalldetailsofvendors(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getalldetailsofvendors_Result>("getalldetailsofvendors", tokenParameter);
        }
    
        public virtual ObjectResult<Getuserwishlistvendors_Result> Getuserwishlistvendors(Nullable<long> wishlistid)
        {
            var wishlistidParameter = wishlistid.HasValue ?
                new ObjectParameter("wishlistid", wishlistid) :
                new ObjectParameter("wishlistid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getuserwishlistvendors_Result>("Getuserwishlistvendors", wishlistidParameter);
        }
    
        public virtual ObjectResult<getallwishlistdetailsofusers_Result> getallwishlistdetailsofusers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallwishlistdetailsofusers_Result>("getallwishlistdetailsofusers");
        }
    
        public virtual ObjectResult<Getwishlistvendorsforadmin_Result> Getwishlistvendorsforadmin(Nullable<long> wishlistid, Nullable<int> categoryid)
        {
            var wishlistidParameter = wishlistid.HasValue ?
                new ObjectParameter("wishlistid", wishlistid) :
                new ObjectParameter("wishlistid", typeof(long));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getwishlistvendorsforadmin_Result>("Getwishlistvendorsforadmin", wishlistidParameter, categoryidParameter);
        }
    }
}
